### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by Pranay1004** [Castorps/Instagram-Bruter#1]
How will the script work on Kali Linux?

**Comment by Castorps** [comment]
I haven't tested it, but it should work. If it doesn't, please provide the output and I'll try to fix it.

**Comment by Pranay1004** [comment]
Hi...I don't how to do so...If u could provide me with the necessary
instructions...would be helpful in this regard

**Comment by Castorps** [comment]
You have to start main.py using python 3.

1. Open a terminal
2. Navigate to Instagram Bruter's directory: `cd /home/your_user/Downloads/InstagramBruter`
3. Start python: `python`,
if it says something like 'Python 3.x.x' this is how you start the script, if it says something like 'Python 2.x.x', try entering `python3` (first exit Python 2 using `exit()`).
3. Exit Python interpreter: `exit()`
4. Start the script:
 `python ./main.py "/home/your_user/combolist" 10`
or (depends on what worked for you in step 3)
`python3 ./main.py "/home/your_user/combolist" 10` 
(whatever parameters you put after `./main.py` is up to you.
5. If the program crashes, copy the text in the terminal and send it to me.

Make sure you have a combolist like how I described it in [this project's description](https://github.com/Castorps/Instagram-Bruter/). 

To build your combolist you need a combomaker (search "combolist maker"), which needs a password list (look for password lists like "rockyou.txt", if you don't want to generate your own).

It didn't work on linux because I used ctypes.windll, but I changed that and now it works on linux and I also fixed a bug concerning the output => download the new version. I'm rather busy atm, so sorry for not being able to respond that quickly!
