### ISSUE TITLE
Program drastically slows down after a few minutes of work

### ISSUE THREAD

**Issue by Januek** [Castorps/Instagram-Bruter#2]
At the beginning everything works well but at a few minutes, the speed of guessing passwords drops to +- 30 passwords/minute.  I think it can be caused by proxy errors (?). How to maintain the initial speed of atack? And what proxy settings should I use to have in use as many proxy as you have on your example screenshot (23000+)?(I have only +-600 when I'm performing an atack, and I think that this may be the reason that my atack speed slows drastically over time).

**Comment by Castorps** [comment]
The reason for the decrease probably is that the script has to wait for proxies being enabled again. There are two scenarios:

1. Proxy tested credentials successfully, proxy can't be used for 10 (default) seconds to avoid blocking
2. Proxy failed to test credentials (instagram returned an error, proxy timeout or other connection-related error), proxy can't be used for 30 (default) seconds

Possible Improvements:

- You could reduce the seconds to wait after a proxy has successfully tested a password by altering proxy_timeout in const.py (try 5 or 7 or something like that). 

- Another solution might be to decrease proxy_success_ratio in const.py to avoid proxies getting removed too fast or unnecessary.

- Increasing proxy_minimum in const.py could help as well.

Btw. I added a feature so the script automatically picks up a session (based on the hash of the combolist you use).

EDIT: I changed the script so that when Instagram returns an error the proxy won't be banned (30 seconds wait time), but just disabled (10 seconds wait time). If Instagram throws an error, it won't affect the proxies tested / retries statistics anymore. That might help in this regard.

EDIT*: Ok I just changed the variables. You can just download it again and see if it works better now.

EDIT**: I updated the proxy scraper, it scrapes all the URLs from the proxy_source file. At the moment it fetches 47k unique proxies.
